function dss_plot_lines(linedata)
%dss_plot_lines Plot the line data
%   Plot line data generated by GridPV.  linedata is either generated from
%   running a new simulation or opening saved data from a CSV file.
%   Each line is plotted as a separate figure.

    linedata_mod = splitvars(convertvars(linedata,{'name','bus1','bus2'},'categorical'));
    
    linedata_s = summary(linedata_mod);
    fldnames = fieldnames(linedata_s);
    
    numlines = height(linedata_s.name.Categories);
    linegraphs = {'bus1PhaseVoltagesPU', 'bus1PhaseCurrent', 'bus1PhasePowerReal','bus1PhasePowerReactive'};
    %graphlabels = {'Bus1 L-N Phase Voltage PU','Bus1 Phase Current', 'Bus1 Phase Real Power', 'Bus1 Phase Reactive Power'};
    
    %linegraphs = {'bus1PhaseVoltagesPU', 'bus2PhaseVoltagesPU'};
      
    %h = figure();
    
    %t = tiledlayout(numlines,length(graphlabels));
    %t = tiledlayout(numlines,1);
    
    linenames = linedata_s.name.Categories;
    
    for i = 1:numlines
    
        fig = figure(i);
    
        bus1name = string(linedata_mod(linedata_mod.name == linenames{i} & linedata_mod.RunNum == 1,{'bus1'}).bus1);
        bus2name = string(linedata_mod(linedata_mod.name == linenames{i} & linedata_mod.RunNum == 1,{'bus2'}).bus2);
    
        %graphlabels = {sprintf('%s L-N Phase Voltage PU',bus1name), sprintf(' %s L-N Phase Voltage PU',bus2name)};
        bus1graphlabels = {strcat(bus1name,' L-N Phase Voltage PU'), strcat(bus1name,' Phase Current'), strcat(bus1name,' Phase Real Power'), strcat(bus1name,' Phase Reactive Power')};
        bus2graphlabels = {strcat(bus2name,' L-N Phase Voltage PU'), strcat(bus2name,' Phase Current'), strcat(bus2name,' Phase Real Power'), strcat(bus2name,' Phase Reactive Power')};

        %nexttile;
    
        tl = tiledlayout(fig, 2,length(bus1graphlabels));
    
        tl.Title.String = sprintf("Line %s",linenames{i});
    
        tbl = linedata_mod(linedata_mod.name == linenames{i},:);
    
        for j = 1:length(linegraphs)
            
            idx = startsWith(fldnames,linegraphs{j});
    
            ax = nexttile;
    
            plot(ax, tbl,'RunNum',fldnames(idx)); 
    
            title(ax,bus1graphlabels{j});
        end

        for j = 1:length(linegraphs)
                
            idx = startsWith(fldnames,linegraphs{j});
        
            ax = nexttile;
        
            plot(ax, tbl,'RunNum',fldnames(idx)); 
        
            title(ax,bus2graphlabels{j});
        end
        %close(h);
    end

end